export FRAMEWORK_MASTER_FILE=
export FRAMEWORK_SLAVE_FILE=workers
export FRAMEWORK_CONF_FILES="spark-env.sh spark-defaults.conf spark-submit scorep.env"
export FRAMEWORK_BIN_DIR="${SPARK_BIN_DIR:-${SPARK_HOME}/bin}"
export FRAMEWORK_NAME="SPARK"